// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "ISC"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Login"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegistrationSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/personal/bids": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Bid"
                ],
                "operationId": "getPersonalBids",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GetPersonalBidsSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/personal/sales": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "getPersonalSales",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Breed",
                        "name": "breed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GetPersonalSalesSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "getAllSales",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Breed",
                        "name": "breed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GetAllSalesSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/:saleID": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "getSale",
                "parameters": [
                    {
                        "type": "string",
                        "description": "saleID",
                        "name": "saleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GetSaleSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/:saleID/bid": {
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Bid"
                ],
                "operationId": "creaateBid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "saleID",
                        "name": "saleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sale.CreateBidSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/:saleID/bids": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Bid"
                ],
                "operationId": "getSaleBids",
                "parameters": [
                    {
                        "type": "string",
                        "description": "saleID",
                        "name": "saleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GetSaleBidsSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/:saleID/cancel": {
            "delete": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "cancelSale",
                "parameters": [
                    {
                        "type": "string",
                        "description": "saleID",
                        "name": "saleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CancelSaleSuccessfulResposnse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/:saleID/republish": {
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "republishSale",
                "parameters": [
                    {
                        "type": "string",
                        "description": "saleID",
                        "name": "saleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CancelSaleSuccessfulResposnse"
                        }
                    }
                }
            }
        },
        "/marketplace/sales/new": {
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "Sale"
                ],
                "operationId": "createSale",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sale.CreateSaleSuccessfulResponse"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "operationId": "profile",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user.GetProfileSuccessfulResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CancelSaleSuccessfulResposnse": {
            "type": "object",
            "properties": {
                "mesage": {
                    "type": "string",
                    "example": "sale cancelled successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetAllSalesSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/sale.GetAllSales"
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched all current sales"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetPersonalBidsSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bid"
                    }
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched all sale bids"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetPersonalSalesSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/sale.GetAllSales"
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched all sale bids"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetSaleBidsSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bid"
                    }
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched all sale bids"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetSaleSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Sale"
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched all current sales"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "Login": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "Register": {
            "type": "object",
            "required": [
                "accountType",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "accountType": {
                    "$ref": "#/definitions/models.AccountType"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.UserAuthData"
                },
                "mesage": {
                    "type": "string",
                    "example": "account created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.RegistrationSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.UserAuthData"
                },
                "mesage": {
                    "type": "string",
                    "example": "account created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.UserAuthData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.AccountType": {
            "type": "string",
            "enum": [
                "BUYER",
                "SELLER"
            ],
            "x-enum-varnames": [
                "BUYER",
                "SELLER"
            ]
        },
        "models.Bid": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string",
                    "readOnly": true,
                    "example": "2022-08-21 21:08"
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "saleId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.Sale": {
            "type": "object",
            "properties": {
                "bidCount": {
                    "type": "integer"
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bid"
                    }
                },
                "breed": {
                    "type": "string"
                },
                "category": {
                    "type": "string",
                    "example": "DOG"
                },
                "createdAt": {
                    "type": "string",
                    "readOnly": true,
                    "example": "2022-08-21 21:08"
                },
                "description": {
                    "type": "string"
                },
                "expiresBy": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "priority": {
                    "$ref": "#/definitions/models.SalePriority"
                },
                "sold": {
                    "type": "boolean"
                },
                "soldTo": {
                    "type": "string"
                },
                "startingBig": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/models.SaleStatus"
                },
                "title": {
                    "type": "string"
                },
                "traderId": {
                    "type": "string"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SaleType"
                        }
                    ],
                    "example": "type"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.SalePriority": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "LOW",
                "NORMAL",
                "HIGH"
            ]
        },
        "models.SaleStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "PUBLISHED",
                "CANCELLED",
                "CLOSED"
            ],
            "x-enum-varnames": [
                "PENDING",
                "PUBLISHED",
                "CANCELLED",
                "CLOSED"
            ]
        },
        "models.SaleType": {
            "type": "string",
            "enum": [
                "NEW",
                "PROMOTED",
                "REPUBLISHED"
            ],
            "x-enum-varnames": [
                "NEW",
                "PROMOTED",
                "REPUBLISHED"
            ]
        },
        "models.User": {
            "type": "object",
            "properties": {
                "accountType": {
                    "$ref": "#/definitions/models.AccountType"
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bid"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "readOnly": true,
                    "example": "2022-08-21 21:08"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "password": {
                    "type": "string"
                },
                "profileImg": {
                    "type": "string"
                },
                "sales": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Sale"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wallet": {
                    "$ref": "#/definitions/models.Wallet"
                }
            }
        },
        "models.Wallet": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string",
                    "readOnly": true,
                    "example": "2022-08-21 21:08"
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "sale.CreateBidSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Sale"
                },
                "mesage": {
                    "type": "string",
                    "example": "bid placed successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "sale.CreateSaleSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "bidCount": "0",
                        "breed": "Cat Dog",
                        "category": "CAT",
                        "createdAt": "2023-01-14T02:06:31+01:00",
                        "description": "BDG for sale",
                        "id": "clcv8zrk90000vboy7d4tb5ms",
                        "priority": "1",
                        "sold": "false",
                        "startingBig": "20000",
                        "status": "PENDING",
                        "title": "Bull Dog For Sale",
                        "traderId": "clcnz7h460000s1mo30jmkewi",
                        "type": "NEW",
                        "updatedAt": "2023-01-14T02:06:31+01:00"
                    }
                },
                "mesage": {
                    "type": "string",
                    "example": "sale created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "sale.GetAllSales": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/utils.Pagination"
                },
                "sales": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Sale"
                    }
                }
            }
        },
        "user.GetProfileSuccessfulResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.User"
                },
                "mesage": {
                    "type": "string",
                    "example": "fetched user profile"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.Pagination": {
            "type": "object",
            "properties": {
                "nextPage": {
                    "type": "integer"
                },
                "previousPage": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKey": {
            "type": "apiKey",
            "name": "x-auth-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Pawdot API Service",
	Description:      "Pawdow API Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
